const dummyData = {
  "Andaman and Nicobar Islands": { name: "andaman-and-nicobar-islands", population: "0.4M", capital: "Port Blair", airport: true },
  "Andhra Pradesh": { name: "andhra-pradesh", population: "53M", capital: "Amaravati", airport: true },
  "Arunachal Pradesh": { name: "arunachal-pradesh", population: "1.7M", capital: "Itanagar", airport: true },
  "Assam": { name: "assam", population: "35M", capital: "Dispur", airport: true },
  "Bihar": { name: "bihar", population: "124M", capital: "Patna", airport: true },
  "Chandigarh": { name: "chandigarh", population: "1.1M", capital: "Chandigarh", airport: true },
  "Chhattisgarh": { name: "chhattisgarh", population: "30M", capital: "Raipur", airport: true },
  "Delhi": { name: "delhi", population: "19M", capital: "New Delhi", airport: true },
  "Dadra and Nagar Haveli and Daman and Diu": { name: "dnh-and-dd", population: "0.6M", capital: "Daman", airport: false },
  "Goa": { name: "goa", population: "1.5M", capital: "Panaji", airport: true },
  "Gujarat": { name: "gujarat", population: "63M", capital: "Gandhinagar", airport: true },
  "Haryana": { name: "haryana", population: "28M", capital: "Chandigarh", airport: true },
  "Himachal Pradesh": { name: "himachal-pradesh", population: "7M", capital: "Shimla", airport: false },
  "Jammu and Kashmir": { name: "jammu-and-kashmir", population: "13M", capital: "Srinagar/Jammu", airport: true },
  "Jharkhand": { name: "jharkhand", population: "39M", capital: "Ranchi", airport: false },
  "Karnataka": { name: "karnataka", population: "64M", capital: "Bengaluru", airport: true },
  "Kerala": { name: "kerala", population: "35M", capital: "Thiruvananthapuram", airport: true },
  "Ladakh": { name: "ladakh", population: "0.3M", capital: "Leh", airport: true },
  "Lakshadweep": { name: "lakshadweep", population: "0.06M", capital: "Kavaratti", airport: false },
  "Madhya Pradesh": { name: "madhya-pradesh", population: "85M", capital: "Bhopal", airport: true },
  "Maharashtra": { name: "maharashtra", population: "123M", capital: "Mumbai", airport: true },
  "Manipur": { name: "manipur", population: "3M", capital: "Imphal", airport: true },
  "Meghalaya": { name: "meghalaya", population: "3M", capital: "Shillong", airport: false },
  "Mizoram": { name: "mizoram", population: "1.1M", capital: "Aizawl", airport: false },
  "Nagaland": { name: "nagaland", population: "2M", capital: "Kohima", airport: true },
  "Odisha": { name: "odisha", population: "45M", capital: "Bhubaneswar", airport: true },
  "Puducherry": { name: "puducherry", population: "1.5M", capital: "Puducherry", airport: false },
  "Punjab": { name: "punjab", population: "30M", capital: "Chandigarh", airport: false },
  "Rajasthan": { name: "rajasthan", population: "81M", capital: "Jaipur", airport: true },
  "Sikkim": { name: "sikkim", population: "0.7M", capital: "Gangtok", airport: true },
  "Tamil Nadu": { name: "tamilnadu", population: "78M", capital: "Chennai", airport: true },
  "Telangana": { name: "telangana", population: "39M", capital: "Hyderabad", airport: true },
  "Tripura": { name: "tripura", population: "4M", capital: "Agartala", airport: false },
  "Uttarakhand": { name: "uttarakhand", population: "11M", capital: "Dehradun", airport: true },
  "Uttar Pradesh": { name: "uttar-pradesh", population: "231M", capital: "Lucknow", airport: true },
  "West Bengal": { name: "west-bengal", population: "100M", capital: "Kolkata", airport: true }
};

  
  
export default dummyData;